---
kind: pipeline
type: docker
name: fiber-frontend

steps:
  - name: build
    image: harbor.jinhun.moe/library/mdbook-builder:latest
    commands:
      - mdbook build
  - name: publish
    image: plugins/docker:latest
    settings:
      dockerfile: Dockerfile
      tag:
        - latest
        - ${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: https://harbor.jinhun.moe
      repo: harbor.jinhun.moe/library/doc_share
  - name: depoly
    image: harbor.jinhun.moe/library/depoly:latest
    settings:
      host:
        from_secret: depoly_host
      username: 
        from_secret: depoly_username
      key:
        from_secret: depoly_key
      script:
        from_secret: depoly_script
     

image_pull_secrets:
  - dockerconfig
