---
kind: pipeline
type: docker
name: hk

steps:
  - name: build
    image: harbor.jinhun.moe/library/mdbook_builder:v0.4.21
    commands:
      - mdbook build

  - name: publish
    image: plugins/docker:latest
    settings:
      dockerfile: .drone/Dockerfile
      tag:
        - latest
        - ${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: https://harbor.jinhun.moe
      repo: harbor.jinhun.moe/library/doc_share

  - name: deploy
    image: harbor.jinhun.moe/drone/deploy:latest
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_username
      key:
        from_secret: deploy_key
      script:
        from_secret: deploy_script

image_pull_secrets:
  - dockerconfig

---
kind: signature
hmac: e008a9cdec013598ee1e77e6ef569de1034f38494c6b748a7bfd042d7ac17a2d
