name: pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup book
        run: |
          chmod u+x assets/bin/* && cp assets/bin/* /usr/local/bin
          git clone https://github.com/MR-Addict/mdbook-repl.git -b gh-pages --depth 1

      - name: Build books
        run: |
          mdbook build --dest-dir github
          echo 'src = "/embed/"' >> book.toml && mdbook build --dest-dir vercel && mv mdbook-repl/embed vercel

      - uses: amondnet/vercel-action@v25
        with:
          vercel-args: --prod
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./vercel

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github
